DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY,
    name TEXT DEFAULT "None",
    url TEXT NOT NULL,
    max_price FLOAT,
    stock INTEGER NOT NULL DEFAULT 0,
    buy INTEGER NOT NULL DEFAULT 0,
    time_stock TEXT DEFAULT CURRENT_TIMESTAMP,
    time_buy TEXT DEFAULT CURRENT_TIMESTAMP,
    active INTEGER NOT NULL DEFAULT 1,
    UNIQUE(name)
);